version: "3.5"
services:
  api:
    networks:
      - piles-calculator-network
    build:
      context: .
    restart: always
    ports:
      - "3040:3040"
networks:
  piles-calculator-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.40.0/24
